version: "3.7"
services:
  # service 1 named react-dev
  react-dev:
    container_name: react-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - NODE_ENV=development